In [14]:
import numpy as np
def vander(x1, N=None, increasing=False):
    x = np.asarray(x1)
    if x.ndim != 1:
        raise ValueError("x must be a one-dimensional array or sequence.")
    if N is None:
        N = len(x)
        
    v = empty((len(x), N), dtype=promote_types(x.dtype, int))
    tmp = v[:, ::-1] if not increasing else v
        
    if N > 0:
        tmp[:, 0] = 1
    if N > 1:
        tmp[:, 1:] = x[:, None]
        multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)
    return v

x1 = np.array([1,3,5,7])
N = 4
np.vander(x1,N)


array([[  1,   1,   1,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1],
       [343,  49,   7,   1]])

In [18]:
np.vander(x1,4,increasing=False)

array([[  1,   1,   1,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1],
       [343,  49,   7,   1]])

In [19]:
np.vander(x1,4,increasing=True)

array([[  1,   1,   1,   1],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125],
       [  1,   7,  49, 343]])